version: "3"

services:
  dev:
    build: ./
    working_dir: /app/
    volumes:
      - ./:/app/
    environment:
      APP_VERSION: ${APP_VERSION-0.1.0\-snapshot}
      TWINE_USERNAME: ${TWINE_USERNAME}
      TWINE_PASSWORD: ${TWINE_PASSWORD}
      TWINE_REPOSITORY_URL: ${TWINE_REPOSITORY_URL}
      TWINE_NON_INTERACTIVE: ${TWINE_NON_INTERACTIVE}
