pipelines:
  snacker-tracker-scanner-test:
    group: snacker-tracker-scanner
    label_template: "${git-snacker-tracker-scanner[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? *"
      only_on_changes: yes
    environment_variables:
      GO_AUTOMATION_USER: automaton
      GITEA_AUTOMATION_USER: gocd-service-account
    secure_variables:
      GO_AUTOMATION_PASSWORD: "AES:+heX4S6WsUXSqPxj5nNOoQ==:9jXtfK+GoUYDpS7mvGGWmA=="
      GITEA_AUTOMATION_PASSWORD: "AES:TxO4rONwgQuFtw+wCZedlA==:P8GY6KrulvsxavOGQHYNvA=="
    materials:
      git-snacker-tracker-scanner:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/scanner.git
          branchwhitelist: master,test-*
        destination: ./

    stages:
      - build-package:
          tasks:
            - script: |
                set -e

                finish() {
                  ./auto/clean-up
                }

                trap finish EXIT


                ./auto/in-docker ./auto/test

      - dummy-stage:
          tasks:
            - script: |
                set -e

  snacker-tracker-scanner-build:
    group: snacker-tracker-scanner
    label_template: "0.1.${COUNT}-${git-snacker-tracker-scanner[:8]}"
    lock_behavior: unlockWhenFinished
    environment_variables:
      GO_AUTOMATION_USER: automaton
      GITEA_AUTOMATION_USER: gocd-service-account
    secure_variables:
      GO_AUTOMATION_PASSWORD: "AES:+heX4S6WsUXSqPxj5nNOoQ==:9jXtfK+GoUYDpS7mvGGWmA=="
      GITEA_AUTOMATION_PASSWORD: "AES:TxO4rONwgQuFtw+wCZedlA==:P8GY6KrulvsxavOGQHYNvA=="
    materials:
      git-snacker-tracker-scanner:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/scanner.git
          branchwhitelist: master,test-*
        destination: ./
      upstream:
        pipeline: snacker-tracker-scanner-test
        stage: dummy-stage

    stages:
      - build-package:
          tasks:
            - script: |
                set -e

                finish() {
                  ./auto/clean-up
                }

                trap finish EXIT

                export APP_VERSION="$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')"

                ./auto/in-docker ./auto/build
                ./auto/test-install
          artifacts:
            - build:
                source: dist/

      - dummy-stage:
          tasks:
            - script: |
                set -e


  snacker-tracker-scanner-publish-test:
    group: snacker-tracker-scanner
    label_template: "${upstream}"
    locking: "on"
    environment_variables:
      TWINE_USERNAME: "__token__"
      TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
      TWINE_NON_INTERACTIVE: "true"
    secure_variables:
      TWINE_PASSWORD: "AES:NLLQgO/6Shxm61HhDsF61g==:QLJOs7Iqo0ZD+yg2w6HkH9l/A6p7HsDXQ7al3sh9wWHvkW6gfP3edX9JV/E78ilDmzMv8qg7xxr68ak1QLMLTHWXyNmlF82gjPjtfE/e6DPTP/E855dGDZcEJxfsBfaT8sIpLi0t9FRf+8heLiPSKg5lA57vN38LZPsgLdlamjEEDt5+tVmDWqztl1mKNhqLk4xdvj0GEPS06XisF8KDGxlI4NNCtKmHfhU7D7CIxUNOXvQkGHT/Q2JHAwHq7yAK"
    materials:
      upstream:
        pipeline: snacker-tracker-scanner-build
        stage: dummy-stage
      git-snacker-tracker-scanner:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/scanner.git
          branchwhitelist: master,test-*
        destination: ./

    stages:
      - publish-test:
          tasks:
            - fetch:
                pipeline: snacker-tracker-scanner-build
                stage: build-package
                job: build-package
                source: dist/
                destination: ./
            - script: |
                set -e

                finish() {
                  ./auto/clean-up
                }

                trap finish EXIT


                ./auto/publish

  snacker-tracker-scanner-publish-prod:
    group: snacker-tracker-scanner
    label_template: "${upstream}"
    locking: "on"
    environment_variables:
      TWINE_USERNAME: "__token__"
      TWINE_NON_INTERACTIVE: "true"
    secure_variables:
      TWINE_PASSWORD: "AES:QZ7Q8ynnQH3oIGbRRY31rQ==:9g9BuHmv5FNkUbj/nqOtCbVbmjtdsPgptMm0ZYTeWEvrwTq5PVrvkcMzxg75m2a27oZPo46SdvXA9CWMu0DCeZboZ3gRIPL3627nzCMHCczR/w4wuLYnL8lMBg0eyzjV8LEjGZBIIES0ovi2IrhtJLmU0luyTKWefuAQFNuLWpAZLvze+GTm56NrrCuOtktUztGIGGHRGnrhMxY+iUBhJjSEKWY6xB6uHtyowQNRT6I="
    materials:
      upstream:
        pipeline: snacker-tracker-scanner-publish-test
        stage: publish-test
      git-snacker-tracker-scanner:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/snacker-tracker/scanner.git
          branchwhitelist: master,test-*
        destination: ./

    stages:
      - publish-prod:
          tasks:
            - fetch:
                pipeline: snacker-tracker-scanner-build/snacker-tracker-scanner-publish-test
                stage: build-package
                job: build-package
                source: dist/
                destination: ./
            - script: |
                set -e

                finish() {
                  ./auto/clean-up
                }

                trap finish EXIT


                ./auto/publish
